from .forms import (
    ProcessPathForm,
    ProcessForm,
    ProcessStepForm,
    ParametersForm,
    InputsForm,
)
from itertools import product

from process_navigator.models.process import Process, ProcessStep, StepParam, StepInput
from process_navigator.extensions.database import db


# this class deals with presenting the data to the user
# namely, about their current Cauldron configuration
# E.g. if they pick to multiple variable values, they will have multiple paths
# or it they repeat a particaular process, they will have multiple entities
class PathData:
    def __init__(self, form: ProcessPathForm):
        self.form = form
        self.number_of_processes = len(form.processes)
        self.paths = self.expand_paths()
        self.number_of_paths = len(self.paths)

    def expand_paths(self):
        all_combinations = []
        for process in self.form.processes:
            process_combinations = self._expand_process(process)
            all_combinations.append(process_combinations)

        # Generate all combinations of processes
        expanded_paths = list(product(*all_combinations))
        return expanded_paths

    def _expand_process(self, process):
        step_combinations = []

        # collate all expanded step combinations
        for step in process.process_steps:
            step_combinations.append(self._expand_step(step))

        # Generate all combinations of steps within a process
        process_combinations = list(product(*step_combinations))
        return process_combinations

    def _expand_step(self, step):
        # get all inputs within a step and get their product
        input_combinations = self._calculate_combinations(step.inputs)

        # get all parameters within a step and get their product
        parameter_combinations = self._calculate_combinations(step.parameters)

        # Generate all combinations of inputs and parameters within a step
        step_combinations = list(product(input_combinations, parameter_combinations))
        return step_combinations

    def _calculate_combinations(self, items):
        if not items:
            return [()]
        return list(product(*[item.values for item in items]))


class Path:
    def __init__(self):
        self.processes = []


# this class deals with commit the data to the database
# for Process and Process Steps there are no multiple value options
# for Inputs and Parametes, as we come across multiple values we will need to copy Path objects
# however, this is complicated by the fact that each object will have an id generated by the database
class PathCommit:
    def __init__(self, form: ProcessPathForm):
        self.form = form

        # start off with one empty Path object
        self.paths = [Path()]

    def generate_db_objects(self):
        for process in self.form.processes:
            self._generate_process(process)

    def _generate_process(self, process: ProcessForm):
        new_process = Process(process_date=process.process_date.data)
        db.session.add(new_process)
        db.session.commit()

        for step_index, step in enumerate(process.process_steps, start=1):
            self._generate_step(new_process, step, step_index)

    def _generate_step(self, process: Process, step: ProcessStepForm, order: int):
        new_step = ProcessStep(
            process_id=process.id,
            process_method_part_id=step.process_method_part.data.id,
            order=order,
            process=process,
            process_method_part=step.process_method_part.data,
        )

        db.session.add(new_step)
        db.session.commit()

        for parameter_index, parameter in enumerate(step.parameters):
            self._generate_step_parameter(parameter, new_step, parameter_index)

        for input_index, input in enumerate(step.inputs):
            self._generate_step_input(input, new_step, input_index)

    def _generate_step_parameter(
        self, parameter: ParametersForm, step: ProcessStep, value_index: int
    ):
        value = parameter.values[value_index].value.data
        print("value: ", value)
        new_step_parameter = StepParam(
            param_id=parameter.parameter.data.id,
            process_step_id=step.id,
            value=value,
            param=parameter.parameter.data,
            process_step=step,
        )

        db.session.add(new_step_parameter)
        db.session.commit()

    def _generate_step_input(
        self, input: InputsForm, step: ProcessStep, value_index: int
    ):
        value = input.values[value_index].value.data
        new_step_input = StepInput(
            input_id=input.input.data.id,
            process_step_id=step.id,
            value=value,
            input=input.input.data,
            process_step=step,
        )
        db.session.add(new_step_input)
        db.session.commit()

    def _copy_path(self):
        pass

    def _copy_process(self, process_to_copy: Process):
        new_process = Process(
            process_date=process_to_copy.process_date,
        )

        db.session.add(new_process)
        db.session.commit()
